### ISSUE TITLE
Specifying e.g. `node_size = 16` does not seem to work

### ISSUE THREAD

**Issue by jhollway** [stocnet/manynet#76] opened 2024-07-20 12:19 UTC
```
graphr(ison_adolescents, node_size = 10)
graphr(ison_adolescents, node_size = 16)
```

**Comment by henriquesposito** [comment] 2024-07-23 09:46
This issue was also caused by the changes in latest releases with how node sizing is done in `graphr()`. This should be fixed now.

**Closed** 2024-07-24 07:00 UTC
Labels: bug
