### ISSUE TITLE
Should be able to assign colours to all nodes, e.g. `node_color = "green"` in `graphr()`

### ISSUE THREAD

**Issue by jhollway** [stocnet/manynet#73] opened 2024-06-21 18:13 UTC
`network::is.color(node_color)` might be useful to recognise when strings can be colors

**Comment by henriquesposito** [comment] 2024-07-23 09:14
This issue was caused by the changes in latest releases with how variable mapping is done in `graphr()`. This should be fixed now.

**Closed** 2024-07-24 07:00 UTC
